#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

case "$1" in
  help | deploy-image:help)
    help_content_func() {
      #shellcheck disable=SC2034
      declare desc="return help_content string"

      cat<<help_content
    deploy-image:deploy <image> <app> , Pull <image> and rebuild <app>
help_content
    }

    if [[ $1 = "deploy-image:help" ]]; then
      echo -e 'Usage: dokku deploy-image[:COMMAND] [<image>]'
      echo ''
      echo 'Run Docker commands.'
      echo ''
      echo 'Example: '
      echo '$ dokku deploy-image:deploy <image>'
      echo ''
      echo -e 'Additional commands:'
      help_content_func | sort | column -c2 -t -s,
    else
      cat<<help_desc
    deploy-image, Plugin for deploy docker images
help_desc
    fi
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;

esac
